# 京东 Cookie + Wskey 抓取 (Quantumult X 资源订阅)
# 订阅地址: https://raw.githubusercontent.com/xiaotaiye88/qx-jd-scripts/master/jd_scripts.conf

[rewrite_local]
^https?://api\.m\.jd\.com/ url script-request-header https://raw.githubusercontent.com/xiaotaiye88/qx-jd-scripts/master/qx_jd_all.js

[mitm]
hostname = api.m.jd.com
