[task_local]
# 拼多多果园任务（每天 1,7,12,18,22 点各跑一次）
30 1,7,12,18,22 * * * https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/pinduoduo/pdd_guoyuan.js, tag=拼多多果园, img-url=https://raw.githubusercontent.com/58xinian/icon/master/jingxi.png, enabled=true
