# 拼多多脚本 (Quantumult X 订阅)
# 用法: 圈X → 设置 → 资源解析器 → 添加订阅 → 粘贴此地址
# 订阅: https://raw.githubusercontent.com/xiaotaiye88/qx-jd-scripts/master/pdd_scripts.conf

[task_local]
# 拼多多果园任务（每天 1,7,12,18,22 点各跑一次）
30 1,7,12,18,22 * * * https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/pinduoduo/pdd_guoyuan.js, tag=拼多多果园, img-url=https://raw.githubusercontent.com/58xinian/icon/master/jingxi.png, enabled=true
